dist: trusty
language: csharp
solution: EnglishParser.sln
mono: none
dotnet: 2.2.401
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE english_parser_test;'
install:
  - dotnet restore
before_script:
  - mv -f travis.ini EnglishParser.DB.Tests/TestDatabase.ini
script:
  - dotnet test
