dist: xenial
language: csharp
solution: EnglishParser.sln
mono: none
dotnet: 2.2.401
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE english_parser_test;'
install:
  - dotnet restore
before_script:
  - cp -f travis.ini EnglishParser.DB.Tests/EnglishParser.DB.Tests.ini
  - cp -f travis.ini EnglishParser.Core.Tests/EnglishParser.Core.Tests.ini
  - cp -f travis.ini EnglishParser.Utils.Tests/EnglishParser.Utils.Tests.ini
script:
  - dotnet test
