SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO `dict_adj` (`base`, `adverb`) VALUES
('daily', 'daily'),
('dying', 'dyingly'),
('early', 'early'),
('easy', 'easily'),
('economic', 'economically'),
('fast', 'fast'),
('good', 'well'),
('hard', 'hard'),
('high', 'high'),
('late', 'late'),
('nonpublic', 'nonpublicly'),
('public', 'publicly'),
('straight', 'straight'),
('wrong', 'wrong');

INSERT INTO `dict_def` (`syn_set_id`, `definition`) VALUES
(1, 'that which is perceived or known or inferred to have its own distinct existence (living or nonliving)'),
(2, 'any of various tailless stout-bodied amphibians with long hind limbs for leaping; semiaquatic and terrestrial species'),
(3, 'a decorative loop of braid or cord'),
(4, 'a person of French nationality');

INSERT INTO `dict_noun` (`base`, `plural`, `female`, `female_plural`) VALUES
('Frenchman', 'Frenchmen', 'Frenchwoman', 'Frenchwomen'),
('Negro', 'Negros', 'Negress', 'Negresses'),
('actor', 'actors', 'actress', 'actresses'),
('addendum', 'addenda', NULL, NULL),
('administrator', 'administrators', 'administratrix', 'administratrixes'),
('aircraft', 'aircraft', NULL, NULL),
('alumna', 'alumnae', NULL, NULL),
('alumnus', 'alumni', NULL, NULL),
('analysis', 'analyses', NULL, NULL),
('antenna', 'antennae', NULL, NULL),
('antithesis', 'antitheses', NULL, NULL),
('apex', 'apices', NULL, NULL),
('appendix', 'appendices', NULL, NULL),
('author', 'authors', 'authoress', 'authoresses'),
('axis', 'axes', NULL, NULL),
('bachelor', 'bachelors', 'spinster', 'spinsters'),
('bacillus', 'bacilli', NULL, NULL),
('bacterium', 'bacteria', NULL, NULL),
('basis', 'bases', NULL, NULL),
('beau', 'beaux', NULL, NULL),
('bison', 'bison', NULL, NULL),
('boy', 'boys', 'girl', 'girls'),
('brave', 'braves', 'squaw', 'squaws'),
('bridegroom', 'bridegrooms', 'bride', 'brides'),
('brother', 'brothers', 'sister', 'sisters'),
('buffalo', 'buffaloes', NULL, NULL),
('bureau', 'bureaux', NULL, NULL),
('cactus', 'cacti', NULL, NULL),
('calf', 'calves', NULL, NULL),
('cattle', 'cattle', NULL, NULL),
('child', 'children', NULL, NULL),
('château', 'châteaux', NULL, NULL),
('cod', 'cod', NULL, NULL),
('codex', 'codices', NULL, NULL),
('concerto', 'concerti', NULL, NULL),
('conductor', 'conductors', 'conductress', 'conductresses'),
('corpus', 'corpora', NULL, NULL),
('count', 'counts', 'countess', 'countesses'),
('crisis', 'crises', NULL, NULL),
('criterion', 'criteria', NULL, NULL),
('curriculum', 'curricula', NULL, NULL),
('czar', 'czars', 'czarina', 'czarinas'),
('dad', 'dads', 'mum', 'mums'),
('daddy', 'daddies', 'mummy', 'mummies'),
('datum', 'data', NULL, NULL),
('deer', 'deer', NULL, NULL),
('diagnosis', 'diagnoses', NULL, NULL),
('die', 'dice', NULL, NULL),
('domino', 'dominoes', NULL, NULL),
('duke', 'dukes', 'duchess', 'duchesses'),
('dwarf', 'dwarves', NULL, NULL),
('echo', 'echoes', NULL, NULL),
('ellipsis', 'ellipses', NULL, NULL),
('embargo', 'embargoes', NULL, NULL),
('emperor', 'emperors', 'empress', 'empresses'),
('entity', 'entities', NULL, NULL),
('epoch', 'epochs', NULL, NULL),
('erratum', 'errata', NULL, NULL),
('father', 'fathers', 'mother', 'mothers'),
('father-in-law', 'father-in-laws', 'mother-in-law', 'mother-in-laws'),
('faux pas', 'faux pas', NULL, NULL),
('fez', 'fezzes', NULL, NULL),
('fiance', 'fiances', 'fiancee', 'fiancees'),
('fish', 'fish', NULL, NULL),
('focus', 'foci', NULL, NULL),
('foot', 'feet', NULL, NULL),
('formula', 'formulae', NULL, NULL),
('frog', 'frogs', NULL, NULL),
('fungus', 'fungi', NULL, NULL),
('gentleman', 'gentlemen', 'lady', 'ladies'),
('genus', 'genera', NULL, NULL),
('ghetto', 'ghettoes', NULL, NULL),
('giant', 'giants', 'giantess', 'giantesses'),
('god', 'gods', 'goddess', 'goddesses'),
('goose', 'geese', NULL, NULL),
('governor', 'governors', 'matron', 'matrons'),
('graffito', 'graffiti', NULL, NULL),
('grandfather', 'grandfathers', 'grandmother', 'grandmothers'),
('grandson', 'grandsons', 'granddaughter', 'granddaughters'),
('grouse', 'grouse', NULL, NULL),
('half', 'halves', NULL, NULL),
('headmaster', 'headmasters', 'headmistress', 'headmistresses'),
('heir', 'heirs', 'heiress', 'heiresses'),
('hero', 'heroes', 'heroine', 'heroines'),
('hoof', 'hooves', NULL, NULL),
('host', 'hosts', 'hostess', 'hostesses'),
('hunter', 'hunters', 'huntress', 'huntresses'),
('husband', 'husbands', 'wife', 'wives'),
('hypothesis', 'hypotheses', NULL, NULL),
('index', 'indices', NULL, NULL),
('innuendo', 'innuendoes', NULL, NULL),
('king', 'kings', 'queen', 'queens'),
('knife', 'knives', NULL, NULL),
('lad', 'lads', 'lass', 'lasses'),
('landlord', 'landlords', 'landlady', 'landladies'),
('larva', 'larvae', NULL, NULL),
('leaf', 'leaves', NULL, NULL),
('libretto', 'libretti', NULL, NULL),
('life', 'lives', NULL, NULL),
('loaf', 'loaves', NULL, NULL),
('locus', 'loci', NULL, NULL),
('lord', 'lords', 'lady', 'ladies'),
('louse', 'lice', NULL, NULL),
('male', 'males', 'female', 'females'),
('man', 'men', 'woman', 'women'),
('manager', 'managers', 'manageress', 'manageresses'),
('mango', 'mangoes', NULL, NULL),
('manservant', 'manservants', 'maidservant', 'maidservants'),
('masseur', 'masseurs', 'masseuse', 'masseuses'),
('master', 'masters', 'mistress', 'mistresses'),
('matrix', 'matrices', NULL, NULL),
('mayor', 'mayors', 'mayoress', 'mayoresses'),
('medium', 'media', NULL, NULL),
('memorandum', 'memoranda', NULL, NULL),
('milkman', 'milkmen', 'milkmaid', 'milkmaids'),
('millionaire', 'millionaires', 'millionairess', 'millionairesses'),
('minutia', 'minutiae', NULL, NULL),
('monitor', 'monitors', 'monitress', 'monitresses'),
('monk', 'monks', 'nun', 'nuns'),
('moose', 'moose', NULL, NULL),
('mosquito', 'mosquitoes', NULL, NULL),
('motto', 'mottoes', NULL, NULL),
('mouse', 'mice', NULL, NULL),
('murderer', 'murderers', 'murderess', 'murderesses'),
('nebula', 'nebulae', NULL, NULL),
('nephew', 'nephews', 'niece', 'nieces'),
('nucleus', 'nuclei', NULL, NULL),
('oasis', 'oases', NULL, NULL),
('offspring', 'offspring', NULL, NULL),
('opus', 'opera', NULL, NULL),
('ovum', 'ova', NULL, NULL),
('ox', 'oxen', NULL, NULL),
('papa', 'papas', 'mama', 'mamas'),
('parenthesis', 'parentheses', NULL, NULL),
('penny', 'pence', NULL, NULL),
('person', 'people', NULL, NULL),
('phenomenon', 'phenomena', NULL, NULL),
('phylum', 'phyla', NULL, NULL),
('poet', 'poets', 'poetess', 'poetesses'),
('policeman', 'policemen', 'policewoman', 'policewomen'),
('postman', 'postmen', 'postwoman', 'postwomen'),
('postmaster', 'postmasters', 'postmistress', 'postmistresses'),
('potato', 'potatoes', NULL, NULL),
('priest', 'priests', 'prietess', 'prietesses'),
('prince', 'princes', 'princess', 'princesses'),
('prognosis', 'prognoses', NULL, NULL),
('prophet', 'prophets', 'prophetess', 'prophetesses'),
('proprietor', 'proprietors', 'proprietress', 'proprietresses'),
('prosecutor', 'prosecutors', 'prosecutrix', 'prosecutrixes'),
('protector', 'protectors', 'protectress', 'protectresses'),
('quiz', 'quizzes', NULL, NULL),
('radius', 'radii', NULL, NULL),
('referendum', 'referenda', NULL, NULL),
('salmon', 'salmon', NULL, NULL),
('scarf', 'scarves', NULL, NULL),
('scissors', 'scissors', NULL, NULL),
('self', 'selves', NULL, NULL),
('series', 'series', NULL, NULL),
('sheep', 'sheep', NULL, NULL),
('shelf', 'shelves', NULL, NULL),
('shepherd', 'shepherds', 'shepherdess', 'shepherdesses'),
('shrimp', 'shrimp', NULL, NULL),
('sir', 'sirs', 'madam', 'madams'),
('son', 'sons', 'daughter', 'daughters'),
('son-in-law', 'son-in-laws', 'daughter-in-law', 'daughter-in-laws'),
('spadefoot', 'spadefeet', NULL, NULL),
('species', 'species', NULL, NULL),
('step-father', 'step-fathers', 'step-mother', 'step-mothers'),
('step-son', 'step-sons', 'step-daughter', 'step-daughters'),
('steward', 'stewards', 'stewardess', 'stewardesses'),
('stimulus', 'stimuli', NULL, NULL),
('stomach', 'stomachs', NULL, NULL),
('stratum', 'strata', NULL, NULL),
('sultan', 'sultans', 'sultana', 'sultanas'),
('swine', 'swine', NULL, NULL),
('syllabus', 'syllabi', NULL, NULL),
('symposium', 'symposia', NULL, NULL),
('synopsis', 'synopses', NULL, NULL),
('tableau', 'tableaux', NULL, NULL),
('tailor', 'tailors', 'tailoress', 'tailoresses'),
('testator', 'testators', 'testatrix', 'testatrixes'),
('thesis', 'theses', NULL, NULL),
('thief', 'thieves', NULL, NULL),
('toad', 'toads', NULL, NULL),
('tomato', 'tomatoes', NULL, NULL),
('tooth', 'teeth', NULL, NULL),
('tornado', 'tornadoes', NULL, NULL),
('torpedo', 'torpedoes', NULL, NULL),
('trousers', 'trousers', NULL, NULL),
('trout', 'trout', NULL, NULL),
('tuna', 'tuna', NULL, NULL),
('uncle', 'uncles', 'aunt', 'aunts'),
('usher', 'ushers', 'usherette', 'usherettes'),
('vertebra', 'vertebrae', NULL, NULL),
('vertex', 'vertices', NULL, NULL),
('veto', 'vetoes', NULL, NULL),
('vita', 'vitae', NULL, NULL),
('volcano', 'volcanoes', NULL, NULL),
('vortex', 'vortices', NULL, NULL),
('waiter', 'waiters', 'waitress', 'waitresses'),
('washerman', 'washermen', 'washerwoman', 'washerwomen'),
('wharf', 'wharves', NULL, NULL),
('widower', 'widowers', 'widow', 'widows'),
('wizard', 'wizards', 'witch', 'witches'),
('wolf', 'wolves', NULL, NULL),
('zero', 'zeroes', NULL, NULL);

INSERT INTO `dict_verb` (`base`, `past_tense`, `past_part`, `pres_part`, `third_pers`) VALUES
('abide', 'abided', 'abided', 'abiding', 'abides'),
('ache', 'ached', 'ached', 'aching', 'aches'),
('acknow', 'acknew', 'acknown', 'acknowwing', 'acknows'),
('adraw', 'adrew', 'adrawn', 'adrawwing', 'adraws'),
('ake', 'oke', 'aken', 'aking', 'akes'),
('alight', 'alighted', 'alighted', 'alighting', 'alights'),
('alight', 'alit', 'alit', 'alighting', 'alights'),
('arise', 'arose', 'arisen', 'arising', 'arises'),
('awake', 'awoke', 'awoken', 'awaking', 'awakes'),
('babysit', 'babysat', 'babysat', 'babysitting', 'babysits'),
('backlight', 'backlighted', 'backlighted', 'backlighting', 'backlights'),
('backlight', 'backlit', 'backlit', 'backlighting', 'backlights'),
('backslide', 'backslid', 'backslid', 'backsliding', 'backslides'),
('backslide', 'backslid', 'backslidden', 'backsliding', 'backslides'),
('be', 'were', 'been', 'bing', 'is'),
('bear', 'bore', 'born', 'bearing', 'bears'),
('bear', 'bore', 'borne', 'bearing', 'bears'),
('beat', 'beat', 'beat', 'beating', 'beats'),
('beat', 'beat', 'beaten', 'beating', 'beats'),
('become', 'became', 'become', 'becoming', 'becomes'),
('bedo', 'bedid', 'bedone', 'bedoing', 'bedoes'),
('bedraw', 'bedrew', 'bedrawn', 'bedrawwing', 'bedraws'),
('bedream', 'bedreamed', 'bedreamed', 'bedreaming', 'bedreams'),
('bedream', 'bedreamt', 'bedreamt', 'bedreaming', 'bedreams'),
('bedrive', 'bedrove', 'bedriven', 'bedriving', 'bedrives'),
('bedwell', 'bedwelled', 'bedwelled', 'bedwelling', 'bedwells'),
('bedwell', 'bedwelt', 'bedwelt', 'bedwelling', 'bedwells'),
('befall', 'befell', 'befallen', 'befalling', 'befalls'),
('befight', 'befought', 'befought', 'befighting', 'befights'),
('beget', 'begot', 'begot', 'begetting', 'begets'),
('beget', 'begot', 'begotten', 'begetting', 'begets'),
('begin', 'began', 'begun', 'beginning', 'begins'),
('bego', 'bewent', 'begone', 'begoing', 'begos'),
('behear', 'beheard', 'beheard', 'behearing', 'behears'),
('behold', 'beheld', 'beheld', 'beholding', 'beholds'),
('beken', 'bekenned', 'bekenned', 'bekenning', 'bekens'),
('beken', 'bekent', 'bekent', 'bekenning', 'bekens'),
('beknit', 'beknit', 'beknit', 'beknitting', 'beknits'),
('beknit', 'beknitted', 'beknitted', 'beknitting', 'beknits'),
('belay', 'belaid', 'belaid', 'belaying', 'belays'),
('belead', 'beled', 'beled', 'beleading', 'beleads'),
('beleap', 'beleaped', 'beleaped', 'beleaping', 'beleaps'),
('beleap', 'beleapt', 'beleapt', 'beleaping', 'beleaps'),
('beleave', 'beleft', 'beleft', 'beleaving', 'beleaves'),
('bend', 'bent', 'bent', 'bending', 'bends'),
('bequeath', 'bequeathed', 'bequeathed', 'bequeathing', 'bequeaths'),
('bequeath', 'bequethed', 'bequethed', 'bequeathing', 'bequeaths'),
('bequeath', 'bequod', 'bequethen', 'bequeathing', 'bequeaths'),
('bequeath', 'bequoth', 'bequoth', 'bequeathing', 'bequeaths'),
('bereave', 'bereaved', 'bereaved', 'bereaving', 'bereaves'),
('bereave', 'bereft', 'bereft', 'bereaving', 'bereaves'),
('besee', 'besaw', 'beseen', 'beseeing', 'besees'),
('beseek', 'besought', 'besought', 'beseeking', 'beseeks'),
('beset', 'beset', 'beset', 'besetting', 'besets'),
('beshine', 'beshined', 'beshined', 'beshining', 'beshines'),
('beshine', 'beshone', 'beshone', 'beshining', 'beshines'),
('bespeak', 'bespoke', 'bespoken', 'bespeaking', 'bespeaks'),
('bespread', 'bespread', 'bespread', 'bespreading', 'bespreads'),
('bestrew', 'bestrewed', 'bestrewed', 'bestrewwing', 'bestrews'),
('bestrew', 'bestrewed', 'bestrewn', 'bestrewwing', 'bestrews'),
('bestride', 'bestrode', 'bestridden', 'bestriding', 'bestrides'),
('bet', 'bet', 'bet', 'betting', 'bets'),
('bet', 'betted', 'betted', 'betting', 'bets'),
('betake', 'betook', 'betaken', 'betaking', 'betakes'),
('betee', 'beteed', 'beteed', 'beteeing', 'betees'),
('betee', 'betow', 'betown', 'beteeing', 'betees'),
('beweep', 'beweeped', 'beweeped', 'beweeping', 'beweeps'),
('beweep', 'bewept', 'bewept', 'beweeping', 'beweeps'),
('bid', 'bid', 'bid', 'bidding', 'bids'),
('bide', 'bided', 'bided', 'biding', 'bides'),
('bide', 'bode', 'bidden', 'biding', 'bides'),
('bind', 'bound', 'bound', 'binding', 'binds'),
('bite', 'bit', 'bitten', 'biting', 'bites'),
('bleed', 'bled', 'bled', 'bleeding', 'bleeds'),
('blow', 'blew', 'blown', 'blowwing', 'blows'),
('break', 'broke', 'broken', 'breaking', 'breaks'),
('breastfeed', 'breastfed', 'breastfed', 'breastfeeding', 'breastfeeds'),
('breed', 'bred', 'bred', 'breeding', 'breeds'),
('bring', 'brought', 'brought', 'bringing', 'brings'),
('broadcast', 'broadcast', 'broadcast', 'broadcasting', 'broadcasts'),
('browbeat', 'browbeat', 'browbeat', 'browbeating', 'browbeats'),
('browbeat', 'browbeat', 'browbeaten', 'browbeating', 'browbeats'),
('build', 'built', 'built', 'building', 'builds'),
('bust', 'bust', 'bust', 'busting', 'busts'),
('bust', 'busted', 'busted', 'busting', 'busts'),
('buy', 'bought', 'bought', 'buying', 'buys'),
('can', 'could', '', '', 'can'),
('cast', 'cast', 'cast', 'casting', 'casts'),
('catch', 'caught', 'caught', 'catching', 'catches'),
('chide', 'chid', 'chid', 'chiding', 'chides'),
('chide', 'chided', 'chidden', 'chiding', 'chides'),
('chide', 'chided', 'chided', 'chiding', 'chides'),
('choose', 'chose', 'chosen', 'choosing', 'chooses'),
('clad', 'clad', 'clad', 'cladding', 'clads'),
('clap', 'clapped', 'clapped', 'clapping', 'claps'),
('clearcut', 'clearcut', 'clearcut', 'clearcutting', 'clearcuts'),
('cleave', 'cleaved', 'cleaved', 'cleaving', 'cleaves'),
('cleave', 'cleft', 'cleft', 'cleaving', 'cleaves'),
('cleave', 'clove', 'cloven', 'cleaving', 'cleaves'),
('clepe', 'cleped', 'cleped', 'cleping', 'clepes'),
('clepe', 'clepen', 'cleped', 'cleping', 'clepes'),
('cling', 'clung', 'clung', 'clinging', 'clings'),
('clothe', 'clad', 'clad', 'clothing', 'clothes'),
('clothe', 'clothed', 'clothed', 'clothing', 'clothes'),
('comb', 'combed', 'combed', 'combing', 'combs'),
('comb', 'combed', 'kempt', 'combing', 'combs'),
('come', 'came', 'come', 'coming', 'comes'),
('come', 'came', 'comen', 'coming', 'comes'),
('cost', 'cost', 'cost', 'costing', 'costs'),
('cost', 'costed', 'costed', 'costing', 'costs'),
('cowrite', 'cowrote', 'cowritten', 'cowriting', 'cowrites'),
('creep', 'creeped', 'creeped', 'creeping', 'creeps'),
('creep', 'crept', 'crept', 'creeping', 'creeps'),
('crosscut', 'crosscut', 'crosscut', 'crosscutting', 'crosscuts'),
('cut', 'cut', 'cut', 'cutting', 'cuts'),
('deal', 'dealt', 'dealt', 'dealing', 'deals'),
('dig', 'dug', 'dug', 'digging', 'digs'),
('dive', 'dived', 'dived', 'diving', 'dives'),
('dive', 'dove', 'dove', 'diving', 'dives'),
('do', 'did', 'done', 'doing', 'does'),
('dow', 'dought', 'dought', 'dowwing', 'dows'),
('dow', 'dowed', 'dowed', 'dowwing', 'dows'),
('downcast', 'downcast', 'downcast', 'downcasting', 'downcasts'),
('downdraw', 'downdrew', 'downdrawn', 'downdrawwing', 'downdraws'),
('draw', 'drew', 'drawn', 'drawwing', 'draws'),
('dream', 'dreamed', 'dreamed', 'dreaming', 'dreams'),
('dream', 'dreamt', 'dreamt', 'dreaming', 'dreams'),
('dress', 'dressed', 'dressed', 'dressing', 'dresses'),
('drink', 'drank', 'drunk', 'drinking', 'drinks'),
('drive', 'drove', 'driven', 'driving', 'drives'),
('dwell', 'dwelled', 'dwelled', 'dwelling', 'dwells'),
('dwell', 'dwelt', 'dwelt', 'dwelling', 'dwells'),
('earn', 'earned', 'earned', 'earning', 'earns'),
('earn', 'earnt', 'earnt', 'earning', 'earns'),
('eat', 'ate', 'eaten', 'eating', 'eats'),
('fall', 'fell', 'fallen', 'falling', 'falls'),
('feed', 'fed', 'fed', 'feeding', 'feeds'),
('feel', 'felt', 'felt', 'feeling', 'feels'),
('fight', 'fought', 'fought', 'fighting', 'fights'),
('find', 'found', 'found', 'finding', 'finds'),
('fit', 'fit', 'fit', 'fitting', 'fits'),
('fit', 'fitted', 'fitted', 'fitting', 'fits'),
('flee', 'fled', 'fled', 'fleeing', 'flees'),
('fling', 'flung', 'flung', 'flinging', 'flings'),
('fly', 'flew', 'flown', 'flying', 'flies'),
('forbear', 'forbore', 'forborn', 'forbearing', 'forbears'),
('forbear', 'forbore', 'forborne', 'forbearing', 'forbears'),
('forbid', 'forbad', 'forbidden', 'forbidding', 'forbids'),
('forbid', 'forbade', 'forbidden', 'forbidding', 'forbids'),
('forbid', 'forbid', 'forbidden', 'forbidding', 'forbids'),
('forecast', 'forecast', 'forecast', 'forecasting', 'forecasts'),
('forefeel', 'forefelt', 'forefelt', 'forefeeling', 'forefeels'),
('forego', 'forewent', 'foregone', 'foregoing', 'foregos'),
('forehear', 'foreheard', 'foreheard', 'forehearing', 'forehears'),
('foreken', 'forekenned', 'forekenned', 'forekenning', 'forekens'),
('foreken', 'forekent', 'forekent', 'forekenning', 'forekens'),
('foreknow', 'foreknew', 'foreknown', 'foreknowwing', 'foreknows'),
('forelay', 'forelaid', 'forelaid', 'forelaying', 'forelays'),
('forelie', 'forelay', 'forelain', 'forelieing', 'forelies'),
('foreread', 'foreread', 'foreread', 'forereading', 'forereads'),
('forerun', 'foreran', 'forerun', 'forerunning', 'foreruns'),
('foresee', 'foresaw', 'foreseen', 'foreseeing', 'foresees'),
('foreshow', 'foreshowed', 'foreshowed', 'foreshowwing', 'foreshows'),
('foreshow', 'foreshowed', 'foreshown', 'foreshowwing', 'foreshows'),
('forespeak', 'forespoke', 'forespoken', 'forespeaking', 'forespeaks'),
('foretell', 'foretold', 'foretold', 'foretelling', 'foretells'),
('forfret', 'forfretted', 'forfretted', 'forfretting', 'forfrets'),
('forfret', 'forfretted', 'forfretten', 'forfretting', 'forfrets'),
('forget', 'forgot', 'forgotten', 'forgetting', 'forgets'),
('forgive', 'forgave', 'forgiven', 'forgiving', 'forgives'),
('forgo', 'forwent', 'forgone', 'forgoing', 'forgos'),
('forlay', 'forlaid', 'forlaid', 'forlaying', 'forlays'),
('forleave', 'forleft', 'forleft', 'forleaving', 'forleaves'),
('forlend', 'forlent', 'forlent', 'forlending', 'forlends'),
('forlet', 'forlet', 'forlet', 'forletting', 'forlets'),
('forlie', 'forlay', 'forlain', 'forlieing', 'forlies'),
('forsake', 'forsook', 'forsaken', 'forsaking', 'forsakes'),
('forsay', 'forsaid', 'forsaid', 'forsaying', 'forsays'),
('forspeak', 'forspoke', 'forspoken', 'forspeaking', 'forspeaks'),
('forspread', 'forspread', 'forspread', 'forspreading', 'forspreads'),
('forstand', 'forstood', 'forstood', 'forstanding', 'forstands'),
('forswear', 'forswore', 'forsworn', 'forswearing', 'forswears'),
('forswink', 'forswank', 'forswunk', 'forswinking', 'forswinks'),
('forswink', 'forswonk', 'forswunken', 'forswinking', 'forswinks'),
('fortee', 'forteed', 'forteed', 'forteeing', 'fortees'),
('fortee', 'fortow', 'fortown', 'forteeing', 'fortees'),
('forthcome', 'forthcame', 'forthcome', 'forthcoming', 'forthcomes'),
('forthlead', 'forthled', 'forthled', 'forthleading', 'forthleads'),
('forthleap', 'forthleaped', 'forthleaped', 'forthleaping', 'forthleaps'),
('forthleap', 'forthleapt', 'forthleapt', 'forthleaping', 'forthleaps'),
('forthtell', 'forthtold', 'forthtold', 'forthtelling', 'forthtells'),
('forwear', 'forweared', 'forweared', 'forwearing', 'forwears'),
('forwear', 'forwore', 'forworn', 'forwearing', 'forwears'),
('freeze', 'froze', 'frozen', 'freezing', 'freezes'),
('fret', 'frate', 'fretten', 'fretting', 'frets'),
('fret', 'fretted', 'fretted', 'fretting', 'frets'),
('frostbite', 'frostbit', 'frostbitten', 'frostbiting', 'frostbites'),
('gainsay', 'gainsaid', 'gainsaid', 'gainsaying', 'gainsays'),
('get', 'got', 'got', 'getting', 'gets'),
('get', 'got', 'gotten', 'getting', 'gets'),
('ghostwrite', 'ghostwrote', 'ghostwritten', 'ghostwriting', 'ghostwrites'),
('gild', 'gilded', 'gilded', 'gilding', 'gilds'),
('gild', 'gilt', 'gilt', 'gilding', 'gilds'),
('give', 'gave', 'given', 'giving', 'gives'),
('go', 'went', 'gone', 'going', 'gos'),
('grave', 'graved', 'graved', 'graving', 'graves'),
('grave', 'grove', 'graven', 'graving', 'graves'),
('grind', 'grinded', 'grinded', 'grinding', 'grinds'),
('grind', 'ground', 'ground', 'grinding', 'grinds'),
('grow', 'grew', 'grown', 'growwing', 'grows'),
('hack', 'hacked', 'hacked', 'hacking', 'hacks'),
('hamstring', 'hamstrung', 'hamstrung', 'hamstringing', 'hamstrings'),
('handset', 'handset', 'handset', 'handsetting', 'handsets'),
('handsew', 'handsewed', 'handsewed', 'handsewwing', 'handsews'),
('handsew', 'handsewed', 'handsewn', 'handsewwing', 'handsews'),
('handspring', 'handsprang', 'handsprung', 'handspringing', 'handsprings'),
('handspring', 'handsprung', 'handsprung', 'handspringing', 'handsprings'),
('handwrite', 'handwrote', 'handwritten', 'handwriting', 'handwrites'),
('hang', 'hanged', 'hanged', 'hanging', 'hangs'),
('hang', 'hung', 'hung', 'hanging', 'hangs'),
('have', 'had', 'had', 'having', 'has'),
('hear', 'heard', 'heard', 'hearing', 'hears'),
('help', 'helped', 'helped', 'helping', 'helps'),
('hew', 'hewed', 'hewed', 'hewwing', 'hews'),
('hew', 'hewed', 'hewn', 'hewwing', 'hews'),
('hide', 'hid', 'hidden', 'hiding', 'hides'),
('hit', 'hit', 'hit', 'hitting', 'hits'),
('hoist', 'hoist', 'hoist', 'hoisting', 'hoists'),
('hoist', 'hoisted', 'hoisted', 'hoisting', 'hoists'),
('hold', 'held', 'held', 'holding', 'holds'),
('housesit', 'housesat', 'housesat', 'housesitting', 'housesits'),
('hurt', 'hurt', 'hurt', 'hurting', 'hurts'),
('inbreed', 'inbred', 'inbred', 'inbreeding', 'inbreeds'),
('inhold', 'inheld', 'inheld', 'inholding', 'inholds'),
('inlay', 'inlaid', 'inlaid', 'inlaying', 'inlays'),
('inlead', 'inled', 'inled', 'inleading', 'inleads'),
('input', 'input', 'input', 'inputting', 'inputs'),
('inset', 'inset', 'inset', 'insetting', 'insets'),
('intake', 'intook', 'intaken', 'intaking', 'intakes'),
('interbreed', 'interbred', 'interbred', 'interbreeding', 'interbreeds'),
('intercut', 'intercut', 'intercut', 'intercutting', 'intercuts'),
('interlay', 'interlaid', 'interlaid', 'interlaying', 'interlays'),
('interweave', 'interwove', 'interwoven', 'interweaving', 'interweaves'),
('keep', 'kept', 'kept', 'keeping', 'keeps'),
('ken', 'kenned', 'kenned', 'kenning', 'kens'),
('ken', 'kent', 'kent', 'kenning', 'kens'),
('kneel', 'kneeled', 'kneeled \'\'', 'kneeling', 'kneels'),
('kneel', 'knelt', 'knelt', 'kneeling', 'kneels'),
('knit', 'knit', 'knit', 'knitting', 'knits'),
('knit', 'knitted', 'knitted', 'knitting', 'knits'),
('know', 'knew', 'known', 'knowwing', 'knows'),
('lade', 'laded', 'laded', 'lading', 'lades'),
('lade', 'laded', 'laden', 'lading', 'lades'),
('lay', 'laid', 'laid', 'laying', 'lays'),
('lead', 'led', 'led', 'leading', 'leads'),
('lean', 'leaned', 'leaned', 'leaning', 'leans'),
('lean', 'leant', 'leant', 'leaning', 'leans'),
('leap', 'leaped', 'leaped', 'leaping', 'leaps'),
('leap', 'leapt', 'leapt', 'leaping', 'leaps'),
('learn', 'learned', 'learned', 'learning', 'learns'),
('learn', 'learnt', 'learnt', 'learning', 'learns'),
('leave', 'left', 'left', 'leaving', 'leaves'),
('lend', 'lent', 'lent', 'lending', 'lends'),
('let', 'let', 'let', 'letting', 'lets'),
('lie', 'lay', 'lain', 'lieing', 'lies'),
('light', 'lighted', 'lighted', 'lighting', 'lights'),
('light', 'lit', 'lit', 'lighting', 'lights'),
('lipread', 'lipread', 'lipread', 'lipreading', 'lipreads'),
('lose', 'lost', 'lost', 'losing', 'loses'),
('make', 'made', 'made', 'making', 'makes'),
('may', 'might', '', '', 'may'),
('mean', 'meant', 'meant', 'meaning', 'means'),
('meet', 'met', 'met', 'meeting', 'meets'),
('misbecome', 'misbecame', 'misbecome', 'misbecoming', 'misbecomes'),
('misbefall', 'misbefell', 'misbefallen', 'misbefalling', 'misbefalls'),
('misbeget', 'misbegot', 'misbegot', 'misbegetting', 'misbegets'),
('misbeget', 'misbegot', 'misbegotten', 'misbegetting', 'misbegets'),
('miscast', 'miscast', 'miscast', 'miscasting', 'miscasts'),
('mischoose', 'mischose', 'mischosen', 'mischoosing', 'mischooses'),
('misdeal', 'misdealt', 'misdealt', 'misdealing', 'misdeals'),
('misdo', 'misdid', 'misdone', 'misdoing', 'misdoes'),
('misfall', 'misfell', 'misfallen', 'misfalling', 'misfalls'),
('misfeed', 'misfed', 'misfed', 'misfeeding', 'misfeeds'),
('misfit', 'misfit', 'misfit', 'misfitting', 'misfits'),
('misfit', 'misfitted', 'misfitted', 'misfitting', 'misfits'),
('misget', 'misgot', 'misgot', 'misgetting', 'misgets'),
('misget', 'misgot', 'misgotten', 'misgetting', 'misgets'),
('misgive', 'misgave', 'misgiven', 'misgiving', 'misgives'),
('mishear', 'misheard', 'misheard', 'mishearing', 'mishears'),
('mishit', 'mishit', 'mishit', 'mishitting', 'mishits'),
('mishold', 'misheld', 'misheld', 'misholding', 'misholds'),
('miskeep', 'miskept', 'miskept', 'miskeeping', 'miskeeps'),
('misken', 'miskenned', 'miskenned', 'miskenning', 'miskens'),
('misken', 'miskent', 'miskent', 'miskenning', 'miskens'),
('misknow', 'misknew', 'misknown', 'misknowwing', 'misknows'),
('mislay', 'mislaid', 'mislaid', 'mislaying', 'mislays'),
('mislead', 'misled', 'misled', 'misleading', 'misleads'),
('mislearn', 'mislearned', 'mislearned', 'mislearning', 'mislearns'),
('mislearn', 'mislearnt', 'mislearnt', 'mislearning', 'mislearns'),
('misread', 'misread', 'misread', 'misreading', 'misreads'),
('missay', 'missaid', 'missaid', 'missaying', 'missays'),
('missee', 'missaw', 'misseen', 'misseeing', 'missees'),
('missend', 'missent', 'missent', 'missending', 'missends'),
('misset', 'misset', 'misset', 'missetting', 'missets'),
('misshoot', 'misshot', 'misshot', 'misshooting', 'misshoots'),
('misspeak', 'misspoke', 'misspoken', 'misspeaking', 'misspeaks'),
('misspell', 'misspelled', 'misspelled', 'misspelling', 'misspells'),
('misspell', 'misspelt', 'misspelt', 'misspelling', 'misspells'),
('misspend', 'misspent', 'misspent', 'misspending', 'misspends'),
('mistake', 'mistook', 'mistaken', 'mistaking', 'mistakes'),
('mistell', 'mistold', 'mistold', 'mistelling', 'mistells'),
('misthrow', 'misthrew', 'misthrown', 'misthrowwing', 'misthrows'),
('misunderstand', 'misunderstood', 'misunderstood', 'misunderstanding', 'misunderstands'),
('miswed', 'miswed', 'miswed', 'miswedding', 'misweds'),
('miswed', 'miswedded', 'miswedded', 'miswedding', 'misweds'),
('miswrite', 'miswrote', 'miswritten', 'miswriting', 'miswrites'),
('must', '', '', '', 'must'),
('naysay', 'naysaid', 'naysaid', 'naysaying', 'naysays'),
('offlead', 'offled', 'offled', 'offleading', 'offleads'),
('offset', 'offset', 'offset', 'offsetting', 'offsets'),
('onlay', 'onlaid', 'onlaid', 'onlaying', 'onlays'),
('onlead', 'onled', 'onled', 'onleading', 'onleads'),
('ought', '', '', '', 'oughts'),
('outbid', 'outbid', 'outbid', 'outbidding', 'outbids'),
('outbreak', 'outbroke', 'outbroken', 'outbreaking', 'outbreaks'),
('outdo', 'outdid', 'outdone', 'outdoing', 'outdoes'),
('outdraw', 'outdrew', 'outdrawn', 'outdrawwing', 'outdraws'),
('outdrink', 'outdrank', 'outdrunk', 'outdrinking', 'outdrinks'),
('outdwell', 'outdwelled', 'outdwelled', 'outdwelling', 'outdwells'),
('outdwell', 'outdwelt', 'outdwelt', 'outdwelling', 'outdwells'),
('outeat', 'outate', 'outeaten', 'outeating', 'outeats'),
('outfall', 'outfell', 'outfallen', 'outfalling', 'outfalls'),
('outfight', 'outfought', 'outfought', 'outfighting', 'outfights'),
('outfly', 'outflew', 'outflown', 'outflying', 'outflies'),
('outgrow', 'outgrew', 'outgrown', 'outgrowwing', 'outgrows'),
('outhear', 'outheard', 'outheard', 'outhearing', 'outhears'),
('outken', 'outkenned', 'outkenned', 'outkenning', 'outkens'),
('outken', 'outkent', 'outkent', 'outkenning', 'outkens'),
('outlay', 'outlaid', 'outlaid', 'outlaying', 'outlays'),
('outlead', 'outled', 'outled', 'outleading', 'outleads'),
('outleap', 'outleaped', 'outleaped', 'outleaping', 'outleaps'),
('outleap', 'outleapt', 'outleapt', 'outleaping', 'outleaps'),
('output', 'output', 'output', 'outputting', 'outputs'),
('outride', 'outrode', 'outridden', 'outriding', 'outrides'),
('outrun', 'outran', 'outrun', 'outrunning', 'outruns'),
('outsell', 'outsold', 'outsold', 'outselling', 'outsells'),
('outshine', 'beshined', 'beshined', 'outshining', 'outshines'),
('outshine', 'beshone', 'beshone', 'outshining', 'outshines'),
('outspend', 'outspent', 'outspent', 'outspending', 'outspends'),
('outspin', 'outspun', 'outspun', 'outspinning', 'outspins'),
('outspread', 'outspread', 'outspread', 'outspreading', 'outspreads'),
('outstride', 'outstrode', 'outstridden', 'outstriding', 'outstrides'),
('outstrive', 'outstrove', 'outstriven', 'outstriving', 'outstrives'),
('outswear', 'outswore', 'outsworn', 'outswearing', 'outswears'),
('outswim', 'outswam', 'outswum', 'outswimming', 'outswims'),
('outtell', 'outtold', 'outtold', 'outtelling', 'outtells'),
('outthink', 'outthought', 'outthought', 'outthinking', 'outthinks'),
('outthrow', 'outthrew', 'outthrown', 'outthrowwing', 'outthrows'),
('outthrust', 'outthrust', 'outthrust', 'outthrusting', 'outthrusts'),
('outwear', 'outweared', 'outweared', 'outwearing', 'outwears'),
('outwear', 'outwore', 'outworn', 'outwearing', 'outwears'),
('overbear', 'overbore', 'overborn', 'overbearing', 'overbears'),
('overbear', 'overbore', 'overborne', 'overbearing', 'overbears'),
('overbeat', 'overbeat', 'overbeat', 'overbeating', 'overbeats'),
('overbeat', 'overbeat', 'overbeaten', 'overbeating', 'overbeats'),
('overbend', 'overbent', 'overbent', 'overbending', 'overbends'),
('overbid', 'overbid', 'overbid', 'overbidding', 'overbids'),
('overblow', 'overblew', 'overblown', 'overblowwing', 'overblows'),
('overbreed', 'overbred', 'overbred', 'overbreeding', 'overbreeds'),
('overbuild', 'overbuilt', 'overbuilt', 'overbuilding', 'overbuilds'),
('overbuy', 'overbought', 'overbought', 'overbuying', 'overbuys'),
('overcast', 'overcast', 'overcast', 'overcasting', 'overcasts'),
('overclothe', 'overclad', 'overclad', 'overclothing', 'overclothes'),
('overclothe', 'overclothed', 'overclothed', 'overclothing', 'overclothes'),
('overcome', 'overcame', 'overcome', 'overcoming', 'overcomes'),
('overcome', 'overcame', 'overcomen', 'overcoming', 'overcomes'),
('overdo', 'overdid', 'overdone', 'overdoing', 'overdoes'),
('overdraw', 'overdrew', 'overdrawn', 'overdrawwing', 'overdraws'),
('overdrink', 'overdrank', 'overdrunk', 'overdrinking', 'overdrinks'),
('overdrive', 'overdrove', 'overdriven', 'overdriving', 'overdrives'),
('overeat', 'overate', 'overeaten', 'overeating', 'overeats'),
('overfeed', 'overfed', 'overfed', 'overfeeding', 'overfeeds'),
('overfly', 'overflew', 'overflown', 'overflying', 'overflies'),
('overget', 'overgot', 'overgot', 'overgetting', 'overgets'),
('overget', 'overgot', 'overgotten', 'overgetting', 'overgets'),
('overgive', 'overgave', 'overgiven', 'overgiving', 'overgives'),
('overgo', 'overwent', 'overgone', 'overgoing', 'overgos'),
('overgrow', 'overgrew', 'overgrown', 'overgrowwing', 'overgrows'),
('overhang', 'overhanged', 'overhanged', 'overhanging', 'overhangs'),
('overhang', 'overhung', 'overhung', 'overhanging', 'overhangs'),
('overhear', 'overheard', 'overheard', 'overhearing', 'overhears'),
('overhit', 'overhit', 'overhit', 'overhitting', 'overhits'),
('overkeep', 'overkept', 'overkept', 'overkeeping', 'overkeeps'),
('overlade', 'overladed', 'overladed', 'overlading', 'overlades'),
('overlade', 'overladed', 'overladen', 'overlading', 'overlades'),
('overlay', 'overlaid', 'overlaid', 'overlaying', 'overlays'),
('overlead', 'overled', 'overled', 'overleading', 'overleads'),
('overleap', 'overleaped', 'overleaped', 'overleaping', 'overleaps'),
('overleap', 'overleapt', 'overleapt', 'overleaping', 'overleaps'),
('overlearn', 'overlearned', 'overlearned', 'overlearning', 'overlearns'),
('overlearn', 'overlearnt', 'overlearnt', 'overlearning', 'overlearns'),
('overleave', 'overleft', 'overleft', 'overleaving', 'overleaves'),
('overlie', 'overlay', 'overlain', 'overlieing', 'overlies'),
('overpay', 'overpaid', 'overpaid', 'overpaying', 'overpays'),
('override', 'overrode', 'overridden', 'overriding', 'overrides'),
('overrun', 'overran', 'overrun', 'overrunning', 'overruns'),
('oversee', 'oversaw', 'overseen', 'overseeing', 'oversees'),
('oversell', 'oversold', 'oversold', 'overselling', 'oversells'),
('overset', 'overset', 'overset', 'oversetting', 'oversets'),
('oversew', 'oversewed', 'oversewed', 'oversewwing', 'oversews'),
('oversew', 'oversewed', 'oversewn', 'oversewwing', 'oversews'),
('overshake', 'overshook', 'overshaken', 'overshaking', 'overshakes'),
('overshine', 'beshined', 'beshined', 'overshining', 'overshines'),
('overshine', 'beshone', 'beshone', 'overshining', 'overshines'),
('overshoot', 'overshot', 'overshot', 'overshooting', 'overshoots'),
('overshrink', 'overshrank', 'overshrunk', 'overshrinking', 'overshrinks'),
('overshrink', 'overshrunk', 'overshrunken', 'overshrinking', 'overshrinks'),
('oversleep', 'overslept', 'overslept', 'oversleeping', 'oversleeps'),
('overslide', 'overslid', 'overslid', 'oversliding', 'overslides'),
('overslide', 'overslid', 'overslidden', 'oversliding', 'overslides'),
('overspend', 'overspent', 'overspent', 'overspending', 'overspends'),
('overspill', 'overspilled', 'overspilled', 'overspilling', 'overspills'),
('overspill', 'overspilt', 'overspilt', 'overspilling', 'overspills'),
('overspread', 'overspread', 'overspread', 'overspreading', 'overspreads'),
('overstand', 'overstood', 'overstood', 'overstanding', 'overstands'),
('overstrew', 'overstrewed', 'overstrewed', 'overstrewwing', 'overstrews'),
('overstrew', 'overstrewed', 'overstrewn', 'overstrewwing', 'overstrews'),
('overstride', 'overstrode', 'overstridden', 'overstriding', 'overstrides'),
('overstrike', 'overstruck', 'overstricken', 'overstriking', 'overstrikes'),
('overstrike', 'overstruck', 'overstruck', 'overstriking', 'overstrikes'),
('overstring', 'overstrung', 'overstrung', 'overstringing', 'overstrings'),
('overstrive', 'overstrove', 'overstriven', 'overstriving', 'overstrives'),
('overswing', 'overswang', 'overswung', 'overswinging', 'overswings'),
('overswing', 'overswung', 'overswung', 'overswinging', 'overswings'),
('overtake', 'overtook', 'overtaken', 'overtaking', 'overtakes'),
('overthrow', 'overthrew', 'overthrown', 'overthrowwing', 'overthrows'),
('overwear', 'overweared', 'overweared', 'overwearing', 'overwears'),
('overwear', 'overwore', 'overworn', 'overwearing', 'overwears'),
('overwet', 'overwet', 'overwet', 'overwetting', 'overwets'),
('overwet', 'overwetted', 'overwetted', 'overwetting', 'overwets'),
('overwrite', 'overwrote', 'overwritten', 'overwriting', 'overwrites'),
('partake', 'partook', 'partaken', 'partaking', 'partakes'),
('pay', 'paid', 'paid', 'paying', 'pays'),
('plead', 'pleaded', 'pleaded', 'pleading', 'pleads'),
('plead', 'pled', 'pled', 'pleading', 'pleads'),
('podcast', 'podcast', 'podcast', 'podcasting', 'podcasts'),
('precast', 'precast', 'precast', 'precasting', 'precasts'),
('prepay', 'prepaid', 'prepaid', 'prepaying', 'prepays'),
('preset', 'preset', 'preset', 'presetting', 'presets'),
('proofread', 'proofread', 'proofread', 'proofreading', 'proofreads'),
('prove', 'proved', 'proved', 'proving', 'proves'),
('prove', 'proved', 'proven', 'proving', 'proves'),
('put', 'put', 'put', 'putting', 'puts'),
('quit', 'quit', 'quit', 'quitting', 'quits'),
('quit', 'quitted', 'quitted', 'quitting', 'quits'),
('read', 'read', 'read', 'reading', 'reads'),
('reave', 'reaved', 'reaved', 'reaving', 'reaves'),
('reave', 'reft', 'reft', 'reaving', 'reaves'),
('rebid', 'rebid', 'rebid', 'rebidding', 'rebids'),
('rebreak', 'rebroke', 'rebroken', 'rebreaking', 'rebreaks'),
('rebuild', 'rebuilt', 'rebuilt', 'rebuilding', 'rebuilds'),
('recast', 'recast', 'recast', 'recasting', 'recasts'),
('recut', 'recut', 'recut', 'recutting', 'recuts'),
('redeal', 'redealt', 'redealt', 'redealing', 'redeals'),
('redo', 'redid', 'redone', 'redoing', 'redoes'),
('redraw', 'redrew', 'redrawn', 'redrawwing', 'redraws'),
('refind', 'refound', 'refound', 'refinding', 'refinds'),
('refreeze', 'refroze', 'refrozen', 'refreezing', 'refreezes'),
('regrow', 'regrew', 'regrown', 'regrowwing', 'regrows'),
('rehear', 'reheard', 'reheard', 'rehearing', 'rehears'),
('relearn', 'relearned', 'relearned', 'relearning', 'relearns'),
('relearn', 'relearnt', 'relearnt', 'relearning', 'relearns'),
('relight', 'relighted', 'relighted', 'relighting', 'relights'),
('relight', 'relit', 'relit', 'relighting', 'relights'),
('remake', 'remade', 'remade', 'remaking', 'remakes'),
('rend', 'rent', 'rent', 'rending', 'rends'),
('repay', 'repaid', 'repaid', 'repaying', 'repays'),
('reprove', 'reproved', 'reproved', 'reproving', 'reproves'),
('reprove', 'reproved', 'reproven', 'reproving', 'reproves'),
('reread', 'reread', 'reread', 'rereading', 'rereads'),
('rerun', 'reran', 'rerun', 'rerunning', 'reruns'),
('resell', 'resold', 'resold', 'reselling', 'resells'),
('resend', 'resent', 'resent', 'resending', 'resends'),
('reset', 'reset', 'reset', 'resetting', 'resets'),
('reshoe', 'reshod', 'reshodden', 'reshoeing', 'reshoes'),
('reshoe', 'reshod', 'reshoed', 'reshoeing', 'reshoes'),
('reshoe', 'reshoed', 'reshod', 'reshoeing', 'reshoes'),
('reshoot', 'reshot', 'reshot', 'reshooting', 'reshoots'),
('reshow', 'reshowed', 'reshowed', 'reshowwing', 'reshows'),
('reshow', 'reshowed', 'reshown', 'reshowwing', 'reshows'),
('reshut', 'reshut', 'reshut', 'reshutting', 'reshuts'),
('resing', 'resang', 'resung', 'resinging', 'resings'),
('resit', 'resat', 'resat', 'resitting', 'resits'),
('retake', 'retook', 'retaken', 'retaking', 'retakes'),
('retell', 'retold', 'retold', 'retelling', 'retells'),
('rethink', 'rethought', 'rethought', 'rethinking', 'rethinks'),
('retread', 'retrod', 'retrod', 'retreading', 'retreads'),
('retread', 'retrod', 'retrodden', 'retreading', 'retreads'),
('rewed', 'rewed', 'rewed', 'rewedding', 'reweds'),
('rewed', 'rewedded', 'rewedded', 'rewedding', 'reweds'),
('rewind', 'rewound', 'rewound', 'rewinding', 'rewinds'),
('rewrite', 'rewrote', 'rewritten', 'rewriting', 'rewrites'),
('rid', 'rid', 'rid', 'ridding', 'rids'),
('rid', 'rid', 'ridded', 'ridding', 'rids'),
('rid', 'ridded', 'ridden', 'ridding', 'rids'),
('ride', 'rode', 'ridden', 'riding', 'rides'),
('ring', 'rang', 'rung', 'ringing', 'rings'),
('rise', 'rose', 'risen', 'rising', 'rises'),
('rive', 'rived', 'rived', 'riving', 'rives'),
('rive', 'rove', 'riven', 'riving', 'rives'),
('run', 'ran', 'run', 'running', 'runs'),
('saw', 'sawed', 'sawed', 'sawwing', 'saws'),
('saw', 'sawed', 'sawn', 'sawwing', 'saws'),
('say', 'said', 'said', 'saying', 'says'),
('see', 'saw', 'seen', 'seeing', 'sees'),
('seek', 'sought', 'sought', 'seeking', 'seeks'),
('sell', 'sold', 'sold', 'selling', 'sells'),
('send', 'sent', 'sent', 'sending', 'sends'),
('set', 'set', 'set', 'setting', 'sets'),
('sew', 'sewed', 'sewed', 'sewwing', 'sews'),
('sew', 'sewed', 'sewn', 'sewwing', 'sews'),
('shake', 'shook', 'shaken', 'shaking', 'shakes'),
('shall', 'should', '', '', 'shall'),
('shear', 'sheared', 'shorn', 'shearing', 'shears'),
('shear', 'shore', 'sheared \'\'', 'shearing', 'shears'),
('shed', 'shed', 'shed', 'shedding', 'sheds'),
('shine', 'shined', 'shined', 'shining', 'shines'),
('shine', 'shone', 'shone', 'shining', 'shines'),
('shit', 'shat', 'shat', 'shitting', 'shits'),
('shit', 'shit', 'shit', 'shitting', 'shits'),
('shit', 'shitted', 'shitted', 'shitting', 'shits'),
('shite', 'shit', 'shit', 'shiting', 'shites'),
('shite', 'shited', 'shited', 'shiting', 'shites'),
('shoe', 'shod', 'shodden', 'shoeing', 'shoes'),
('shoe', 'shod', 'shoed', 'shoeing', 'shoes'),
('shoe', 'shoed', 'shod', 'shoeing', 'shoes'),
('shoot', 'shot', 'shot', 'shooting', 'shoots'),
('show', 'showed', 'showed', 'showwing', 'shows'),
('show', 'showed', 'shown', 'showwing', 'shows'),
('shrink', 'shrank', 'shrunk', 'shrinking', 'shrinks'),
('shrink', 'shrunk', 'shrunken', 'shrinking', 'shrinks'),
('shrive', 'shrived', 'shrived', 'shriving', 'shrives'),
('shut', 'shut', 'shut', 'shutting', 'shuts'),
('sightsee', 'sightsaw', 'sightseen', 'sightseeing', 'sightsees'),
('simulcast', 'simulcast', 'simulcast', 'simulcasting', 'simulcasts'),
('sing', 'sang', 'sung', 'singing', 'sings'),
('sink', 'sank', 'sunk', 'sinking', 'sinks'),
('sink', 'sunk', 'sunken', 'sinking', 'sinks'),
('sit', 'sat', 'sat', 'sitting', 'sits'),
('slay', 'slayed', 'slayed', 'slaying', 'slays'),
('slay', 'slew', 'slain', 'slaying', 'slays'),
('sleep', 'slept', 'slept', 'sleeping', 'sleeps'),
('slide', 'slid', 'slid', 'sliding', 'slides'),
('slide', 'slid', 'slidden', 'sliding', 'slides'),
('sling', 'slung', 'slung', 'slinging', 'slings'),
('slink', 'slank', 'slank', 'slinking', 'slinks'),
('slink', 'slinked', 'slinked', 'slinking', 'slinks'),
('slink', 'slunk', 'slunk', 'slinking', 'slinks'),
('slip', 'slipped', 'slipped', 'slipping', 'slips'),
('slit', 'slit', 'slit', 'slitting', 'slits'),
('slit', 'slit', 'slitten', 'slitting', 'slits'),
('smell', 'smelled', 'smelled', 'smelling', 'smells'),
('smell', 'smelt', 'smelt', 'smelling', 'smells'),
('smite', 'smote', 'smitted', 'smiting', 'smites'),
('smite', 'smote', 'smitten', 'smiting', 'smites'),
('sneak', 'sneaked', 'sneaked', 'sneaking', 'sneaks'),
('sneak', 'snuck', 'snuck', 'sneaking', 'sneaks'),
('soothsay', 'soothsaid', 'soothsaid', 'soothsaying', 'soothsays'),
('sow', 'sowed', 'sowed', 'sowwing', 'sows'),
('sow', 'sowed', 'sown', 'sowwing', 'sows'),
('speak', 'spoke', 'spoken', 'speaking', 'speaks'),
('speed', 'sped', 'sped', 'speeding', 'speeds'),
('speed', 'speeded', 'speeded', 'speeding', 'speeds'),
('spell', 'spelled', 'spelled', 'spelling', 'spells'),
('spell', 'spelt', 'spelt', 'spelling', 'spells'),
('spend', 'spent', 'spent', 'spending', 'spends'),
('spill', 'spilled', 'spilled', 'spilling', 'spills'),
('spill', 'spilt', 'spilt', 'spilling', 'spills'),
('spin', 'spun', 'spun', 'spinning', 'spins'),
('spit', 'spat', 'spat', 'spitting', 'spits'),
('spit', 'spit', 'spit', 'spitting', 'spits'),
('split', 'split', 'split', 'splitting', 'splits'),
('spoil', 'spoiled', 'spoiled', 'spoiling', 'spoils'),
('spoil', 'spoilt', 'spoilt', 'spoiling', 'spoils'),
('spread', 'spread', 'spread', 'spreading', 'spreads'),
('spring', 'sprang', 'sprung', 'springing', 'springs'),
('spring', 'sprung', 'sprung', 'springing', 'springs'),
('stand', 'stood', 'stood', 'standing', 'stands'),
('starve', 'starved', 'starved', 'starving', 'starves'),
('stave', 'staved', 'staved', 'staving', 'staves'),
('stave', 'stove', 'stove', 'staving', 'staves'),
('steal', 'stole', 'stolen', 'stealing', 'steals'),
('stick', 'stuck', 'stuck', 'sticking', 'sticks'),
('sting', 'stung', 'stung', 'stinging', 'stings'),
('stink', 'stank', 'stunk', 'stinking', 'stinks'),
('stink', 'stunk', 'stunk', 'stinking', 'stinks'),
('strew', 'strewed', 'strewed', 'strewwing', 'strews'),
('strew', 'strewed', 'strewn', 'strewwing', 'strews'),
('stride', 'strode', 'stridden', 'striding', 'strides'),
('strike', 'struck', 'stricken', 'striking', 'strikes'),
('strike', 'struck', 'struck', 'striking', 'strikes'),
('string', 'strung', 'strung', 'stringing', 'strings'),
('strip', 'stripped', 'stripped', 'stripping', 'strips'),
('strip', 'stript', 'stript', 'stripping', 'strips'),
('strive', 'strived', 'strived', 'striving', 'strives'),
('strive', 'strove', 'striven', 'striving', 'strives'),
('sublet', 'sublet', 'sublet', 'subletting', 'sublets'),
('swear', 'swore', 'sworn', 'swearing', 'swears'),
('sweat', 'sweat', 'sweat', 'sweating', 'sweats'),
('sweat', 'sweated', 'sweated', 'sweating', 'sweats'),
('sweep', 'swept', 'swept', 'sweeping', 'sweeps'),
('swell', 'swelled', 'swelled', 'swelling', 'swells'),
('swell', 'swelled', 'swollen', 'swelling', 'swells'),
('swelt', 'swelted', 'swelted', 'swelting', 'swelts'),
('swim', 'swam', 'swum', 'swimming', 'swims'),
('swing', 'swang', 'swung', 'swinging', 'swings'),
('swing', 'swung', 'swung', 'swinging', 'swings'),
('swink', 'swank', 'swinked', 'swinking', 'swinks'),
('swink', 'swank', 'swunk', 'swinking', 'swinks'),
('swink', 'swinked', 'swonken', 'swinking', 'swinks'),
('swink', 'swonk', 'swunken', 'swinking', 'swinks'),
('take', 'took', 'taken', 'taking', 'takes'),
('teach', 'taught', 'taught', 'teaching', 'teaches'),
('tear', 'tore', 'torn', 'tearing', 'tears'),
('tee', 'teed', 'teed', 'teeing', 'tees'),
('tee', 'tow', 'town', 'teeing', 'tees'),
('telecast', 'telecast', 'telecast', 'telecasting', 'telecasts'),
('tell', 'told', 'told', 'telling', 'tells'),
('think', 'thought', 'thought', 'thinking', 'thinks'),
('thrive', 'thrived', 'thrived', 'thriving', 'thrives'),
('thrive', 'throve', 'thriven', 'thriving', 'thrives'),
('throw', 'threw', 'thrown', 'throwwing', 'throws'),
('thrust', 'thrust', 'thrust', 'thrusting', 'thrusts'),
('toswink', 'toswank', 'toswunk', 'toswinking', 'toswinks'),
('toswink', 'toswank', 'toswunken', 'toswinking', 'toswinks'),
('tread', 'trod', 'trod', 'treading', 'treads'),
('tread', 'trod', 'trodden', 'treading', 'treads'),
('typecast', 'typecast', 'typecast', 'typecasting', 'typecasts'),
('umbedraw', 'umbedrew', 'umbedrawn', 'umbedrawwing', 'umbedraws'),
('unbend', 'unbent', 'unbent', 'unbending', 'unbends'),
('unbind', 'unbound', 'unbound', 'unbinding', 'unbinds'),
('unclothe', 'unclad', 'unclad', 'unclothing', 'unclothes'),
('unclothe', 'unclothed', 'unclothed', 'unclothing', 'unclothes'),
('underbear', 'underbore', 'underborn', 'underbearing', 'underbears'),
('underbear', 'underbore', 'underborne', 'underbearing', 'underbears'),
('underbet', 'underbet', 'underbet', 'underbetting', 'underbets'),
('underbet', 'underbetted', 'underbetted', 'underbetting', 'underbets'),
('underbid', 'underbid', 'underbid', 'underbidding', 'underbids'),
('underbind', 'underbound', 'underbound', 'underbinding', 'underbinds'),
('underbuild', 'underbuilt', 'underbuilt', 'underbuilding', 'underbuilds'),
('underbuy', 'underbought', 'underbought', 'underbuying', 'underbuys'),
('undercast', 'undercast', 'undercast', 'undercasting', 'undercasts'),
('underclothe', 'underclad', 'underclad', 'underclothing', 'underclothes'),
('underclothe', 'underclothed', 'underclothed', 'underclothing', 'underclothes'),
('undercut', 'undercut', 'undercut', 'undercutting', 'undercuts'),
('underdig', 'underdug', 'underdug', 'underdigging', 'underdigs'),
('underdo', 'underdid', 'underdone', 'underdoing', 'underdoes'),
('underdraw', 'underdrew', 'underdrawn', 'underdrawwing', 'underdraws'),
('undereat', 'underate', 'undereaten', 'undereating', 'undereats'),
('underfeed', 'underfed', 'underfed', 'underfeeding', 'underfeeds'),
('underget', 'undergot', 'undergot', 'undergetting', 'undergets'),
('underget', 'undergot', 'undergotten', 'undergetting', 'undergets'),
('undergo', 'underwent', 'undergone', 'undergoing', 'undergos'),
('undergrow', 'undergrew', 'undergrown', 'undergrowwing', 'undergrows'),
('underhang', 'underhanged', 'underhanged', 'underhanging', 'underhangs'),
('underhang', 'underhung', 'underhung', 'underhanging', 'underhangs'),
('underhew', 'underhewed', 'underhewed', 'underhewwing', 'underhews'),
('underhew', 'underhewed', 'underhewn', 'underhewwing', 'underhews'),
('underhit', 'underhit', 'underhit', 'underhitting', 'underhits'),
('underkeep', 'underkept', 'underkept', 'underkeeping', 'underkeeps'),
('underlay', 'underlaid', 'underlaid', 'underlaying', 'underlays'),
('underlead', 'underled', 'underled', 'underleading', 'underleads'),
('underlet', 'underlet', 'underlet', 'underletting', 'underlets'),
('underlie', 'underlay', 'underlain', 'underlieing', 'underlies'),
('underpay', 'underpaid', 'underpaid', 'underpaying', 'underpays'),
('underrun', 'underran', 'underrun', 'underrunning', 'underruns'),
('undersee', 'undersaw', 'underseen', 'underseeing', 'undersees'),
('undersell', 'undersold', 'undersold', 'underselling', 'undersells'),
('undershoot', 'undershot', 'undershot', 'undershooting', 'undershoots'),
('undersleep', 'underslept', 'underslept', 'undersleeping', 'undersleeps'),
('underspread', 'underspread', 'underspread', 'underspreading', 'underspreads'),
('understand', 'understood', 'understood', 'understanding', 'understands'),
('undertake', 'undertook', 'undertaken', 'undertaking', 'undertakes'),
('underthrow', 'underthrew', 'underthrown', 'underthrowwing', 'underthrows'),
('underwrite', 'underwrote', 'underwritten', 'underwriting', 'underwrites'),
('undo', 'undid', 'undone', 'undoing', 'undoes'),
('unfreeze', 'unfroze', 'unfrozen', 'unfreezing', 'unfreezes'),
('unhear', 'unheard', 'unheard', 'unhearing', 'unhears'),
('unlay', 'unlaid', 'unlaid', 'unlaying', 'unlays'),
('unlearn', 'unlearned', 'unlearned', 'unlearning', 'unlearns'),
('unlearn', 'unlearnt', 'unlearnt', 'unlearning', 'unlearns'),
('unmake', 'unmade', 'unmade', 'unmaking', 'unmakes'),
('unweave', 'unwove', 'unwoven', 'unweaving', 'unweaves'),
('unwind', 'unwound', 'unwound', 'unwinding', 'unwinds'),
('upcast', 'upcast', 'upcast', 'upcasting', 'upcasts'),
('updraw', 'updrew', 'uprawn', 'updrawwing', 'updraws'),
('upgrow', 'upgrew', 'upgrown', 'upgrowwing', 'upgrows'),
('uphang', 'uphanged', 'uphanged', 'uphanging', 'uphangs'),
('uphang', 'uphung', 'uphung', 'uphanging', 'uphangs'),
('uphold', 'upheld', 'upheld', 'upholding', 'upholds'),
('uplay', 'uplaid', 'uplaid', 'uplaying', 'uplays'),
('uplead', 'upled', 'upled', 'upleading', 'upleads'),
('uprise', 'uprose', 'uprisen', 'uprising', 'uprises'),
('upsell', 'upsold', 'upsold', 'upselling', 'upsells'),
('upset', 'upset', 'upset', 'upsetting', 'upsets'),
('upstand', 'upstood', 'upstood', 'upstanding', 'upstands'),
('upsweep', 'upswept', 'upswept', 'upsweeping', 'upsweeps'),
('upswell', 'upswelled', 'upswelled', 'upswelling', 'upswells'),
('upswell', 'upswelled', 'upswollen', 'upswelling', 'upswells'),
('uptake', 'uptook', 'uptaken', 'uptaking', 'uptakes'),
('uptear', 'uptore', 'uptorn', 'uptearing', 'uptears'),
('upthrow', 'upthrew', 'upthrown', 'upthrowwing', 'upthrows'),
('vex', 'vexed', 'vexed', 'vexing', 'vexes'),
('wake', 'woke', 'woken', 'waking', 'wakes'),
('waylay', 'waylaid', 'waylaid', 'waylaying', 'waylays'),
('wear', 'weared', 'weared', 'wearing', 'wears'),
('wear', 'wore', 'worn', 'wearing', 'wears'),
('weave', 'wove', 'woven', 'weaving', 'weaves'),
('webcast', 'webcast', 'webcast', 'webcasting', 'webcasts'),
('wed', 'wed', 'wed', 'wedding', 'weds'),
('wed', 'wedded', 'wedded', 'wedding', 'weds'),
('weep', 'weeped', 'weeped', 'weeping', 'weeps'),
('weep', 'wept', 'wept', 'weeping', 'weeps'),
('wet', 'wet', 'wet', 'wetting', 'wets'),
('wet', 'wetted', 'wetted', 'wetting', 'wets'),
('will', 'would', '', '', 'will'),
('win', 'won', 'won', 'winning', 'wins'),
('wind', 'wound', 'wound', 'winding', 'winds'),
('withdraw', 'withdrew', 'withdrawn', 'withdrawwing', 'withdraws'),
('withgo', 'withwent', 'withgone', 'withgoing', 'withgos'),
('withhold', 'withheld', 'withheld', 'withholding', 'withholds'),
('withsay', 'withsaid', 'withsaid', 'withsaying', 'withsays'),
('withset', 'withset', 'withset', 'withsetting', 'withsets'),
('withsit', 'withsat', 'withsat', 'withsitting', 'withsits'),
('withstand', 'withstood', 'withstood', 'withstanding', 'withstands'),
('withtake', 'withtook', 'withtaken', 'withtaking', 'withtakes'),
('worth', 'worth', 'worth', 'worthing', 'worths'),
('worth', 'worth', 'worthen', 'worthing', 'worths'),
('worth', 'worthed', 'worthed', 'worthing', 'worths'),
('wring', 'wrang', 'wrung', 'wringing', 'wrings'),
('wring', 'wrung', 'wrung', 'wringing', 'wrings'),
('write', 'wrote', 'written', 'writing', 'writes'),
('zinc', 'zinced', 'zinced', 'zincing', 'zincs'),
('zinc', 'zincked', 'zincked', 'zincing', 'zincs'),
('zinc', 'zinked', 'zinked', 'zincing', 'zincs');

INSERT INTO `dict_word` (`word`, `type`, `syn_set_id`, `word_num`) VALUES
('entity', 0, 1, 1),
('frog', 0, 2, 1),
('toad', 0, 2, 2),
('frog', 0, 3, 1),
('frogs', 0, 3, 2),
('Frenchman', 0, 4, 1),
('Frenchwoman', 0, 4, 2),
('spadefoot', 0, 5, 1),
('easy', 2, 6, 1),
('economic', 2, 7, 1),
('dying', 2, 8, 1),
('nonpublic', 2, 9, 1),
('easily', 3, 10, 2),
('economically', 3, 11, 1),
('hack', 1, 12, 1),
('do', 1, 13, 3),
('can', 1, 14, 1);
SET FOREIGN_KEY_CHECKS=1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
